### ISSUE TITLE
icomoon font redefenition

### ISSUE THREAD

**Issue by pmatos** [claudio-walser/pelican-marble#1]
I think redefining icomoon font in `style.css` is a bug. It's already defined in `icomoon.css`.

https://github.com/claudio-walser/pelican-fh5co-marble/blob/b1264366d1381c87e2940dde5a34383f10ce7c69/static/css/style.css#L2

Why would you have to do it twice?

**Comment by claudio-walser** [comment]
You are absolutely right, I will fix this in the next few days.

**Comment by claudio-walser** [comment]
btw, I hope you don't get disappointed about my response time, i am currently in holiday ;)

**Comment by claudio-walser** [comment]
Fixed in https://github.com/claudio-walser/pelican-fh5co-marble/commit/a86c0aa25add91d8d8b2ee2a44c2a2ef4d64f37f

Thank you
