### ISSUE TITLE
External installation and use

### ISSUE THREAD

**Issue by davins90** [claudio-walser/pelican-marble#10]
Hi Claudio,
i'm new in pelican world and I really appreciate the theme you developed! Is it possible to use it in my blog (under construction)? If yes, how can I install it?
thanks very much,
daniele

**Comment by claudio-walser** [comment]
Hi Daniele

Thank you for your interest in the theme. Of course you can use it for your project. I provide a working example in this repository: https://github.com/claudio-walser/pelican-fh5co-marble-example
Checkout both repositories in the same directory, cd into the example directory and run your pelican commands.

Hope this helps, kind regards
Claudio

**Comment by davins90** [comment]
Hi Claudio!

Thank you very much for your precious help! I'm building the blog as you suggested and it seems pretty nice! I have only a problem with the iconmoon and favicon. I'll attach you the output I get from the cmd. What do you suggest? I try to change the path, but it always seems that it's not working. My problem is that i don't see the icon (of github, arrow, ecc...), but i see only an empty square. What can i do in your opinion, please?
Thanks very much
Daniele

![errore_icon](https://user-images.githubusercontent.com/31472994/79284087-f86a7f80-7eb9-11ea-92ff-a6f4fe715bc0.png)

**Comment by claudio-walser** [comment]
Hi Daniele
In order to get the icons to work, it is very important that you open the page on exactly the url you defined in your pelican config.
In the example, https://github.com/claudio-walser/pelican-fh5co-marble-example/blob/master/pelicanconf.py#L9 
you can view the page only on http://localhost:8081, http://127.0.0.1:8081 wont work.

I need to fix this once i'll find time to work on the theme again.

Kind regards
Claudio

**Comment by claudio-walser** [comment]
Does it work for you? If so, i would close this ticket :-)

**Comment by davins90** [comment]
Hi Claudio!

thanks very much for your patience, I really appreciate :) Unluckily it doesn't work! In the example attached above, I've already set the site URL in pelicanconfig.py to my localhost and port 8000 (or 8081) and then i run the apposite pelican command with the correct port and bing address. Anyway, the icon never appears. Is there any other part of the code that i have to change with the correct IP address? 

I build a pelican static blog for my website, and I'll set your pelican theme to work. Everything is fine at the moment except the icons (at least for the moment) :) In the attachment you'll see a screen of the blog i'm building.
![error_icon_2](https://user-images.githubusercontent.com/31472994/79613400-c138e000-80fe-11ea-8a7e-b40380e6ddbf.png)


thanks very much for your precious help Claudio!

Daniele

**Comment by davins90** [comment]
Sorry if i disturb you, i found also this error in "inspection", thanks very much if you would help me!
![inspection](https://user-images.githubusercontent.com/31472994/79620100-20065580-810f-11ea-9190-f86464628aa8.png)

**Comment by claudio-walser** [comment]
Hi Daniele

Hm, this is strange. It's hard to say without debugging it by myself. Can you provide your repository so i can try it out myself? Or maybe upload your current blog somewhere in order to provide me an url of the result?

Claudio

**Comment by davins90** [comment]
Hi Claudio!

thanks for the fast answer! I've uploaded to my GitHub the blog i'm trying to build. Here the link: 

https://github.com/davins90/prova_20_blog 

In order to run it, in my windows10 PC, i have to: git clone the repo, open the "prova_20_blog" repo, run "pelican "path of the folder 'content'", run "pelican --listen"

I wrote it in order to let you know my passages, maybe i'm making something wrong!
Thanks again for your precious help! :) 

Daniele

**Comment by claudio-walser** [comment]
Weird, the font path in the theme seems broken. Not sure why this would ever have worked to be honest.
Can you tryout the branch "icomoon-fix" of the theme, at least it works for me locally now.
https://github.com/claudio-walser/pelican-fh5co-marble/tree/icomoon-fix

Btw, you are doing everything right and you even fix the cross-origin Issue by letting SITEURL empty in your pelican config. Not sure if you did it by intention but it's very smart ;-)

**Comment by davins90** [comment]
Hi Claudio! :) 

thank you so much! With this improvement now the icon appears :) thank you very much! After that I've added the google maps map after activating an API key as suggested in the google maps documentation. I've some problems with the contact form at the moment, but i hope to solve it in the next days. 
As first step i try to manually modify the PHP as you suggested but it seems not working. So, i'm trying to add an external contact form with the recaptcha from google. I'll let you know (sorry for the inconvenience) :) 
Thank you again Claudio for your precious help! 😄 

Daniele

**Comment by claudio-walser** [comment]
Hi Daniele

No problem, you are welcome. I'll merge the pr then and close this issue. If you need help with the php form, just open a new issue if you like.

Stay healthy and best regards
Claudio
