### ISSUE TITLE
Not find the SCSS file

### ISSUE THREAD

**Issue by tecsoc** [claudio-walser/pelican-marble#12]
Looking at the style.css.map, I think the SCSS file exists.
If the SCSS file exists, I'd like to see it included in the repository as well.
Sorry if I'm wrong.

**Comment by claudio-walser** [comment]
Boy, longt ime ago. I really need to setup notifications for this repo. Sorry for let you wait.
Yes, I feel I should update this repo anytime soon anyway, also for this ugly jquery vulnerability as well. I will include the scss files as well, they exist.

In the meantime, you can download those by yourself, as i stated in the README, this theme is created by freehtml5.co.
You can go there and download everything right away. I basically just templated everything into a pelican theme.

You find the original, including the sass files, here: https://freehtml5.co/preview/?item=marble-free-html5-bootstrap-template-for-portfolio-or-multi-purpose-websites

**Comment by claudio-walser** [comment]
I am going to close this, feel free to open a new issue if you think the answer does not fit your need.
