### ISSUE TITLE
Icons are not rendering

### ISSUE THREAD

**Issue by edemirel** [claudio-walser/pelican-marble#3]
Both in a self built site, and in the example provided, the Social Media and search icons are not rendering. I think this might be because of your build process. It worked when I changed the icomoon css paths to "../fonts/icomoon/icomoon.svg?6py85u#icomoon" etc

**Comment by claudio-walser** [comment]
In order to get the icons to work, it is important that you access the page exactly with url specified in  https://github.com/claudio-walser/pelican-fh5co-marble-example/blob/master/pelicanconf.py#L9
In the examples case, this should be http://localhost:8081

**Comment by claudio-walser** [comment]
I've used this theme on https://www.gitcd.io if you want to check on a live example...
This page is built from https://github.com/gitcd-io/website

**Comment by claudio-walser** [comment]
Did using a proper URL fix your issue?

**Comment by claudio-walser** [comment]
I will close this issue. If the problem still persists for you, feel free to reopen it.

**Comment by rragundez** [comment]
icons are not rendering for me https://rragundez.github.io/
source
 https://github.com/rragundez/rragundez.github.io/tree/source.
