### ISSUE TITLE
Iconmoon icons not appearing

### ISSUE THREAD

**Issue by rragundez** [claudio-walser/pelican-marble#4]
icons are not rendering for me https://rragundez.github.io/
source
https://github.com/rragundez/rragundez.github.io/tree/source.

So I guess I'm missing something

**Comment by claudio-walser** [comment]
This i probably the same issue as here:
https://github.com/claudio-walser/pelican-fh5co-marble/issues/3

Its important to access the page on the same url as defined in pelican.conf
https://github.com/claudio-walser/pelican-fh5co-marble-example/blob/master/pelicanconf.py#L9

Let me know if this fixes your issue. I will check today evening if i could load the icon.css with a relative path and if this fixes the issue.
