### ISSUE TITLE
Question about social icons

### ISSUE THREAD

**Issue by MathieuDepetris** [claudio-walser/pelican-marble#8]
Dear Claudio Walser,
I try to use your pelican theme pelican-fh5co-marble. First of all, thank you very much for all your work done on that.
I have a question related to the insertion of social icons. I try to add them but several work and other not. To be more precise, I don't achieve to add Skype, Viadeo and an mail icons (for example this one https://fontawesome.com/icons/envelope?style=solid)
After research I saw that the social icons are managed by iconmoon. 
Could you please tell me where I can find the exact icon name and list of icons available (maybe I put the wrong name in my pelicanconf.py) ?
A last thing, if my icons doesn't exist in the theme, it's possible for me to add it manually ?
Best regards,
Mathieu

**Comment by claudio-walser** [comment]
Hi Mathieu

Sorry for the long delay, did not see you opened an issue until now.

Icomoon Overview is probably best taken at their page: https://icomoon.io/#preview-free
If you want to extend the social icons, i am afraid you need to edit the template by your self:
https://github.com/claudio-walser/pelican-fh5co-marble/blob/master/templates/partial/social.html

**Comment by MathieuDepetris** [comment]
Dear Claudio Walser,
Thank you very much for your answer, it's worked perfectly !
Best regards,
Mathieu
